# fly_checklist - Flutter Project
name: fly_checklist
description: Este é um aplicativo para gerenciar uma lista de tarefas diárias que se repetem na sua rotina, permitindo que você adicione, edite e remova tarefas conforme necessário.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

# Optional project metadata
homepage: https://github.com/vitoramaral10/fly_checklist
repository: https://github.com/vitoramaral10/fly_checklist
issue_tracker: https://github.com/vitoramaral10/fly_checklist/issues

environment:
  sdk: ^3.8.1
  flutter: ">=3.19.0"

dependencies:
  cloud_firestore: ^6.0.0
  cupertino_icons: ^1.0.8
  firebase_analytics: ^12.0.0
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  firebase_performance: ^0.11.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.7.2
  google_sign_in: ^7.1.1
  intl: ^0.20.2
  package_info_plus: ^8.3.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/